fields:
  password:
    display: Password (Leave blank to deactivate the maintenance page)
    type: text
  title:
    display: Title
    type: text
  subtitle:
    display: Subtitle
    type: text
  button:
    display: Text for the password button
    type: text
  logo:
    display: Logo
    type: assets
    container: main
    max_files: 1
